# Cargo configuration for workflow-optimiser WASM builds[target.wasm32-unknown-unknown]
# Use lld linker for faster builds
rustflags = ["-C", "link-arg=-s"]

# Alias for common commands
[alias]
wasm-build = "build --release --target wasm32-unknown-unknown"
wasm-dev = "build --target wasm32-unknown-unknown"
